// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tucmokfnjpkiqmdsocml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1Y21va2ZuanBraXFtZHNvY21sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MTA0MDMsImV4cCI6MjA2Mzk4NjQwM30.HyPxHxfwoBWQNMRkcZcilyHqM3zQbtmtjihq9GwFqh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);